version: "3.9"

services:
  api:
    image: imagineapi/imagineapi-api:0.2
    environment:
      PUBLIC_URL: ${PUBLIC_URL}
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    depends_on: [rabbitmq]

  bot:
    image: imagineapi/imagineapi-bot:0.2
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
      DISCORD_EMAIL: ${DISCORD_EMAIL}
      DISCORD_PASSWORD: ${DISCORD_PASSWORD}
      DISCORD_SERVER_ID: ${DISCORD_SERVER_ID}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      TWO_CAPTCHA_API_KEY: ${TWO_CAPTCHA_API_KEY}
    depends_on: [rabbitmq]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672"          # management UI
